name: Initialize Template

#
# Run this on creation of a branch or ref
#
on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      #
      # Checkout the code
      #
      - uses: actions/checkout@v2
      
      #
      # Run tmplr with required environment variables
      #
      - name: Setup
        run: npx tmplr
        env:
          owner_name: ${{ github.event.repository.owner.name }}
          owner_email: ${{ github.event.repository.owner.email }}
          repo_name: ${{ github.event.repository.name }}
          repo_url: ${{ github.event.repository.ssh_url }}
      
      #
      # Cleanup stuff so that the workflow doesn't run anymore
      #
      - name: Cleanup
        run: |
          rm -fr .tmplr.yml
          rm -fr .github/workflows/init.yml
      
      #
      # Commit the code
      #
      - uses: actions-x/commit@v1
